version: ‘3.7'

services:
  postgres:
    container_name: keycloak_db
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: tuncode
    volumes:
      - kc-db:/var/lib/postgresql/data

  keycloak:
    container_name: kc_authserver
    image: quay.io/keycloak/keycloak:23.0.6
    command:
      - start-dev
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_PORT: "5432"
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: tuncode
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  kc-db:
  kc-db-all:
