#server:
#  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  profiles:
    active: tr
    default: eng
  datasource:
    url: ENC(CuHOTrVAKh/MGFipOtVEw+jKDUtNTsWtJQy5OHHwNds5C3EO0vfM/h6Y1IkTS2yHYdgAlsz9fIvcy35zsccOQ/f7yP5XEK2Ez8RbdwVjoUWOomlwLsmysAoIBKlIhnZ4)
    username: ENC(UpKOotTkMK+0aRCHmbhi9koAYnMbGWc7oWzFGUbkx/h5QvWx2TlpEJj+27HLLMYG1U6nqklep3v7/UvmpfYYcg==)
    password: ENC(ULykFyR73RmVB2rYw81cPwWyoVlOSdr9BttSsU73kNR2fTodOJXGYMmZfjE//HVE)
#    driver-class-name: org.h2.Driver
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true
#  security:
#    user:
#      name: ENC(pEKivJEVqKBxvOKt3nSWVJt14kz1fzL3c39n2o3cwCUcRQcpbLDAcxaV9h3d+5ph)
#      password: ENC(v1hc6COGOuOgTcg6vtB28pTjBEHfoJN0+o1Pr4Z/KPUDnvP60v3lKZ8hRt4wyv54)

logging:
  pattern:
    console: "%clr(%-5p) %clr(${PID}){cyan} %clr(--->){red} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(--->){red} %clr(%m){faint}%n"