server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/springboot-practices # keycloak realm address
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs # JWT auth public key address
jwt:
  auth:
    converter:
      resource-id: springboot-practices-app # client id
      principle-attribute: preferred_username

logging:
  level:
    org:
      springframework:
        security: DEBUG


