#server:
#  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  profiles:
    active: tr
    default: eng
  datasource:
    url: ENC(RiCa4xMGWfeVEGLuY4oNB/Zok5NxprnPkhHgIGg6R9mQePvRPZi6fVwQMLG62+L0CVHbROp3tDvRlP4rz+Gpcw==)
    username: ENC(WIhLyy1umQV1ZcV9uM0ptC6tIEerSfV+IhazI0s90OINTTLuav6oqlbXF63lXrf6)
    password: ENC(YLJ8W8Nf/9QXevjPSElJIpN4yrS/NhRc9Jx5Mws58UiRZgJzWOtzTQ/bJP8MS3wv)
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true
  security:
    user:
      name: ENC(pEKivJEVqKBxvOKt3nSWVJt14kz1fzL3c39n2o3cwCUcRQcpbLDAcxaV9h3d+5ph)
      password: ENC(v1hc6COGOuOgTcg6vtB28pTjBEHfoJN0+o1Pr4Z/KPUDnvP60v3lKZ8hRt4wyv54)

logging:
  pattern:
    console: "%clr(%-5p) %clr(${PID}){cyan} %clr(--->){red} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(--->){red} %clr(%m){faint}%n"